#!/bin/bash

CMD=$1
WHARF_HOST=$2

# Figure out where the actual script lives,
# so we can find the playbooks
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# Create the hosts inventory file
INVENTORY=/tmp/wharf_hosts.ini
sed 's/HOST/'"$WHARF_HOST"'/' $DIR/hosts.ini > $INVENTORY

# shift the args so that $2 is now $1
# do it twice
shift
shift

if [ -z $CMD ]; then
    echo "Please specify a command: ls, deploy, destroy"
    exit 1

elif [ -z $WHARF_HOST ]; then
    echo "Please specify a wharf host"
    exit 1

elif [ $CMD == 'deploy' ]; then
    APP_NAME=$1
    APP_PORT=$2
    APP_PLAYBOOK=$3
    DOMAIN_NAME=$4
    LETSENCRYPT_EMAIL=$5
    if [ -z $APP_NAME ]; then
        echo "Specify an app name"
        exit 1
    fi
    if [ -z $APP_PORT ]; then
        echo "Specify an app port"
        exit 1
    fi
    if [ -z $APP_PLAYBOOK ]; then
        echo "Specify an app playbook path"
        exit 1
    fi
    if [ -z $DOMAIN_NAME ]; then
        echo "Specify a domain name"
        exit 1
    fi
    if [ -z $LETSENCRYPT_EMAIL ]; then
        echo "Specify a Let's Encrypt email address"
        exit 1
    fi

    ansible-playbook -i $INVENTORY $DIR/deploy.yml \
        -e "app_name=${APP_NAME}" \
        -e "app_port=${APP_PORT}" \
        -e "app_playbook=${APP_PLAYBOOK}" \
        -e "domain_name=${DOMAIN_NAME}" \
    -e "letsencrypt_email=${LETSENCRYPT_EMAIL}"

elif [ $CMD == 'destroy' ]; then
    APP_NAME=$1
    if [ -z $APP_NAME ]; then
        echo "Specify an app name"
        exit 1
    fi

    ansible-playbook -i $INVENTORY $DIR/destroy.yml -e "app_name=${APP_NAME}"

elif [ $CMD == 'ls' ]; then
    ansible wharf -i $INVENTORY -a "/usr/bin/docker ps -a"

else
    echo "Please specify a command: ls, deploy, destroy"
    exit 1

fi